# Generated by Django 4.2.11 on 2025-06-03 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('webadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='webadmin.payment'),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='account.user'),
        ),
        migrations.AddIndex(
            model_name='transactionhistory',
            index=models.Index(fields=['payment'], name='transaction_payment_de33f6_idx'),
        ),
    ]
