# Generated by Django 4.2.11 on 2025-05-18 13:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid
import webadmin.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', webadmin.models.MySQLUUIDField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('image_path', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='account.user')),
            ],
            options={
                'db_table': 'vehicles',
            },
        ),
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('id', webadmin.models.MySQLUUIDField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('space_number', models.CharField(max_length=10)),
                ('level', models.IntegerField()),
                ('is_occupied', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('standard', 'Tiêu chuẩn'), ('compact', 'Nhỏ gọn'), ('large', 'Lớn'), ('handicapped', 'Dành cho người khuyết tật'), ('motorcycle', 'Xe máy')], default='standard', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'parkingspace',
                'unique_together': {('level', 'space_number')},
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_in', models.DateTimeField()),
                ('time_out', models.DateTimeField(blank=True, null=True)),
                ('parking_space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webadmin.parkingspace')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='webadmin.vehicle')),
            ],
            options={
                'db_table': 'histories',
            },
        ),
    ]
