# Generated by Django 4.2.11 on 2025-06-03 21:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid
import webadmin.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_in', models.DateTimeField()),
                ('time_out', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'histories',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', webadmin.models.MySQLUUIDField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('image_path', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='account.user')),
            ],
            options={
                'db_table': 'vehicles',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('history', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='webadmin.history')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('id', webadmin.models.MySQLUUIDField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('space_number', models.CharField(max_length=10)),
                ('level', models.IntegerField()),
                ('is_occupied', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'parkingspace',
                'unique_together': {('level', 'space_number')},
            },
        ),
        migrations.AddField(
            model_name='history',
            name='parking_space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webadmin.parkingspace'),
        ),
        migrations.AddField(
            model_name='history',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='webadmin.vehicle'),
        ),
    ]
