# Generated by Django 4.2.11 on 2025-05-18 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='vehicle_id',
            new_name='vehicle',
        ),
    ]
