# Generated by Django 4.2.11 on 2025-05-18 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webadmin', '0002_rename_vehicle_id_history_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingspace',
            name='type',
        ),
    ]
